### ISSUE TITLE
Fix "expand +/-" css for scrollbar

### ISSUE THREAD

**Issue by itajackass** [lcvriend/wc-multi-selector#5]
Hi I suggest a little fix causing scrollbar "hide" the + (or -) symbol at the right of lists:

    [data-role="group"] > summary::after {
       ....
      margin-right: 9px;
    }

![immagine](https://github.com/lcvriend/wc-multi-selector/assets/17260726/464976c4-b5ba-4526-aa59-038ddaf10350)

**Comment by lcvriend** [comment]
Hi! Thank you for the suggestion (and sorry for the late reply). I think this is mainly an issue in Firefox right? It appears that the scrollbar will overlap with the +/- and also the x in the selection menu. In chrome I notice that the layout shifts a bit when a scrollbar is added. I have added this to the styling:

```css
:host > details[open] > div {
    [...]
    padding-right: calc(var(--ms-main-padding) + 8px);
    [...]
    scrollbar-gutter: stable;
}
```

It adds some space to the right of the selection menu. I don't exactly love how it looks but it does resolve the shifting and overlapping issues with the scrollbar AFAICT.
